name: Build nn_tilde (macOS)
on:
  push:
    tags:
      - "v*"
jobs:
  Build-nn_tilde-macOS:
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - run: git submodule update --init --recursive
      - name: Setup torch
        run: |
          curl https://nubo.ircam.fr/index.php/s/7deSnqxNXJtArxw/download -o libtorch.tar.gz
          tar -xvf libtorch.tar.gz
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ../src -DCMAKE_PREFIX_PATH=${{ github.workspace }}/libtorch -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES=arm64
          make
      - name: Package creation
        run: |
          mkdir nn_tilde
          mv src/externals nn_tilde
          tar -czvf nn_max_msp_macOS_arm64.tar.gz nn_tilde
      - name: Automated Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            nn_max_msp_macOS_arm64.tar.gz
